// Action Types
export const FETCH_BIZ_DATA = 'FETCH_BIZ_DATA';
export const GET_LOCATION = 'GET_LOCATION';
export const SELECTED_CATEGORY = 'SELECTED_CATEGORY';
export const SET_PINNED_BUSINESS_ID_ARR = 'SET_PINNED_BUSINESS_ID_ARR'